### ISSUE TITLE
tag and commit missing for version 1.6.0

### ISSUE THREAD

**Issue by richardlau** [nodejs/nodejs-latest-linker#14]
@MoLow could you push the commit and tag for version 1.6.0 to this repository?

**Comment by MoLow** [comment]
Pushed: 
https://github.com/nodejs/nodejs-latest-linker/releases/tag/v1.6.0
https://github.com/nodejs/nodejs-latest-linker/commit/1bbf05cc0ff42decfd35eea31d3951dae290778c

**Comment by richardlau** [comment]
Thank you!
