### ISSUE TITLE
Rename primary branch to main

### ISSUE THREAD

**Issue by mhdawson** [nodejs/nodejs-latest-linker#8]
We are going through all of the node.js repositories to rename the primary branch to main. Please see nodejs/node#33864 for more context.

There are references to master in githbub workflows but I can update those as part of the change. 

Please let me know if there are any concerns otherwise I'll look to do the rename Friday May 4th.

**Comment by mhdawson** [comment]
@rvagg any concern that the rename might break something?

**Comment by rvagg** [comment]
i don't believe there's anything automatic linked to this repo

**Comment by mhdawson** [comment]
@rvagg thanks, renamed.
